services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Mount the local signal-cli directory to the container
      - ./signal-cli:/root/.local/share/signal-cli
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/wheel_n_deal}
      - SIGNAL_PHONE_NUMBER=${SIGNAL_PHONE_NUMBER}
      - SIGNAL_GROUP_ID=${SIGNAL_GROUP_ID}
      - SECRET_KEY=${SECRET_KEY:-your_secure_secret_key}
    depends_on:
      - broker
      - postgres
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    build: ./backend
    volumes:
      - ./signal-cli:/root/.local/share/signal-cli
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/wheel_n_deal}
      - SIGNAL_PHONE_NUMBER=${SIGNAL_PHONE_NUMBER}
      - SIGNAL_GROUP_ID=${SIGNAL_GROUP_ID}
      - SECRET_KEY=${SECRET_KEY:-your_secure_secret_key}
    depends_on:
      - broker
      - postgres
      - backend
    restart: always
    command: celery -A celery_app worker --loglevel=info

  broker:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wheel_n_deal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  signal-cli-data:
  redis-data:
  postgres-data:
